# -*- coding: utf-8 -*-
"""CatDog.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11XRlxiwt0qJqfo0jm3beeinYo_IsasEj
"""

import numpy as np

#### Convert "Greyhound", "Terrier", "BullDog" to "Dog"
#### Convert "Tabby", "Black", "Siamese" to "Cat"
#### Return converted Array
#### Return Count Cats and Dogs
def convertAnimal(data):
    maskDog = (data == "Terrier") | (data == "BullDog") | (data == "Greyhound")
    maskCat = (data == "Black") | (data == "Tabby") | (data == "Siamese")
    countDog = maskDog.sum()
    countCat = maskCat.sum()
    retArray = data
    retArray[(maskDog)] = "Dog"
    retArray[(maskCat)] = "Cat"

    return retArray, countDog, countCat

##############################################
inputData = np.array(["Terrier",
        "Greyhound",
        "Greyhound",
        "Tabby",
        "Black",
        "Siamese",
        "BullDog",
        "Tabby",
        "Black"])

actual = np.array(["Dog",
        "Dog",
        "Dog",
        "Cat",
        "Cat",
        "Cat",
        "Dog",
        "Cat",
        "Cat"])
  
data,countDog,countCat  = convertAnimal(inputData)

print ("Your result:", data)
print ("Expected result:", actual)
print ("Dog Count: ", countDog)
print ("Cat Count: ", countCat)